@startuml
title Запрос каталога товаров в Shop API

participant Front
participant ShopAPI
participant Cache
database ShopDb

Front -> ShopAPI: Запрос данных каталога
ShopAPI -> Cache: Запрашиваем данные по категории в кеше
alt Данные есть в кеше
    Cache --> ShopAPI: Возвращает данные по категории
else Данных в кеше нет    
    ShopAPI -> ShopDb: Запрашиваем идентификаторы товаров в категории
    ShopDb --> ShopAPI: Возвращает данные
    ShopAPI -> Cache: Обновляем кеш данными из категории
    Cache --> ShopAPI: Подтверждает обновления кеша
end
ShopAPI -> Cache: Запрашивает данные о всех товарах из категории в кеше
Cache --> ShopAPI: Возвращает данные по товарам
opt Не по всем товарам есть информация в кеше 
    ShopAPI -> ShopDb: Запрашиваем информацию по недостающим товарам
    ShopDb --> ShopAPI: Возвращает данные    
    ShopAPI -> Cache: Обновляем кеш данными недостающих товаров
    Cache --> ShopAPI: Подтверждает обновления кеша 
end
ShopAPI -> Front : Возвращает данные о товарах    
    
@enduml
