@startuml
title Запрос данных о заказах в MES API

participant Front
participant MESAPI
participant Cache
database MESDb

Front -> MESAPI: Запрос данных о заказах
MESAPI -> Cache: Запрашиваем идентификаторы заказов по ключу запросу (например, заказы первой страницы)
alt Данные есть в кеше
    Cache --> MESAPI: Возвращает данные по ключу запросу
else Данных в кеше нет    
    MESAPI -> MESDb: Отбираем идентификаторы заказов, подходящих для запроса 
    MESDb --> MESAPI: Возвращает данные
    MESAPI -> Cache: Обновляем кеш полученными данными из результата запроса
    Cache --> MESAPI: Подтверждает обновления кеша
end
MESAPI -> Cache: Запрашивает данные о всех заказах, которые входят в результат запроса
Cache --> MESAPI: Возвращает данные по заказам
opt Не по всем заказам есть информация в кеше 
    MESAPI -> MESDb: Запрашиваем информацию по недостающим заказам
    MESDb --> MESAPI: Возвращает данные    
    MESAPI -> Cache: Обновляем кеш данными недостающих заказов
    Cache --> MESAPI: Подтверждает обновления кеша 
end
MESAPI -> Front : Возвращает данные о заказах    

@enduml
